Fm/docker cfg
bmc-labs/runrs pull request #28
Opened 2024-07-14 10:20 UTC by fabitosh

Extends `Docker` struct to all available advanced parameters of the [GitLab Runners Docker Section](https://archives.docs.gitlab.com/15.11/runner/configuration/advanced-configuration.html#the-runnersdocker-section) and implements a minimum set of sensible defaults.

2024-07-14 10:33 UTC, fabitosh commented on glrcfg/src/runner/executors/docker.rs
> +    pub security_opt: Vec<String>, // todo: serialization needs to use a : instead of the , between elements
Implement a serde serialization for this

2024-07-14 10:33 UTC, fabitosh commented on glrcfg/src/runner/executors/docker.rs
> +    pub device_cgroup_rules: Vec<String>, // https://docs.docker.com/compose/compose-file/05-services/#device_cgroup_rules
Unsure whether that would work like this.

2024-07-14 10:33 UTC, fabitosh commented on glrcfg/src/runner/executors/docker.rs
> +    pub pull_policy: Vec<String>,
Input can actually be String as well as a list of strings.

The list allows for a chaining of multiple policies if the first one fails

2024-07-20 11:12 UTC, cdbrkfxrpt requested changes

2024-07-20 11:12 UTC, cdbrkfxrpt commented on glrcfg/src/runner/executors/docker.rs
> +    }
```suggestion
```

no longer needed with the introduced changes; that aside, we wouldn't _want_ a `None` pull policy to serialize to a `null` value in JSON, would we?

2024-07-20 11:12 UTC, cdbrkfxrpt commented on glrcfg/src/runner/executors/docker.rs
> +        let policy = PullPolicy::Single(Some("single_policy".to_string()));
```suggestion
        let policy = PullPolicy::Single("single_policy".to_string());
```

2024-07-20 18:36 UTC, cdbrkfxrpt approved these changes

2024-07-21 21:08 UTC, cdbrkfxrpt approved these changes

2024-07-21 21:21 UTC, merged